language: php
php:
  - 7.0
  - 7.1
  - 7.2
  - 7.3

services:
  - postgresql
  
install:
  - composer require php-coveralls/php-coveralls

before_script:
  - mkdir -p build/logs

after_success:
  - php vendor/bin/php-coveralls -v

