language: php
php:
  - 7.0
  - 7.1

services:
  - postgresql
  
install:
  - composer require satooshi/php-coveralls

before_script:
  - mkdir -p build/logs

after_success:
  - php vendor/bin/coveralls -v

